# 服务注册中心端口号
server:
  host: http://192.168.19.77
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${server.host}:${server.port}/eureka/
  instance:
    home-page-url-path: ${server.host}:${server.port}
    status-page-url-path: ${server.host}:${server.port}/info
    health-check-url-path: ${server.host}:${server.port}/health

spring:
  cloud:
    client:
      host-name: center-service
